### PR TITLE
Tpn() and tcpn() should be tnp() and tcnp(), fixes #3

### LINKED ISSUE #3: tpn() and tcpn() should be tnp() and tcnp()

### PR DESCRIPTION
**Pull request by iszak**

### CODE REVIEW

**Comment by alexanderwallin** [comment]
Cool stuff, @iszak! Would you mind splitting this into three PRs, so that we can address them separately?

**Comment by iszak** [comment]
@alexanderwallin done!

**Comment by alexanderwallin** [comment]
Sweet. Would you mind just updating the current README with the correct names?

**Comment by iszak** [comment]
@alexanderwallin sure, I expect this would require a v2 as its a backwards incompatible change? Perhaps we could keep the old ones but emit a deprecated warning? is it worth creating a CHANGELOG.md?

**Comment by alexanderwallin** [comment]
Yup, it's a breaking change. It'll be a minor bump from `0.2.2` -> `0.3.0`.

I don't think we need to bother, really, since it had 96 downloads in the last month. ☺️

**Comment by iszak** [comment]
@alexanderwallin updated the read me, I also found another place where I missed `tests/components/T-test.js` so I've updated that. Unfortunately you can't see the difference since I've flattened all changes it into a single commit to prevent a breaking build between commits let me know if you prefer me not to in the future.

I noticed there is still some references to `tpn` in the example build artifacts however I couldn't get it working (npm run example/npm run start in example directory), it fails with the following error
```
ERROR in ../src/index.js
Module not found: Error: Cannot resolve module 'babel' in lioness/src
 @ ../src/index.js 16:23-54
webpack: Failed to compile.
```
This seems broken on master as well so I'm not sure if it's worth fixing for now?

**Comment by alexanderwallin** [comment]
> Unfortunately you can't see the difference since I've flattened all changes it into a single commit to prevent a breaking build between commits let me know if you prefer me not to in the future.

Add separate commits to PRs, and then we can squash them into one commit when merging if we want. Breaking builds in PRs is fine!

> I noticed there is still some references to tpn in the example build artifacts however I couldn't get it working (npm run example/npm run start in example directory), it fails with the following error
> 
> ERROR in ../src/index.js
> Module not found: Error: Cannot resolve module 'babel' in lioness/src
>  @ ../src/index.js 16:23-54
> webpack: Failed to compile.
> 
> This seems broken on master as well so I'm not sure if it's worth fixing for now?

Have you run `npm install` in both the project root and in the examples directory?

**Comment by iszak** [comment]
@alexanderwallin yes I ran `npm install` in both directories, are you able to reproduce?

**Comment by alexanderwallin** [comment]
I deleted my `node_modules` directories too and have the same problem. Debugging it now. Let me know if you find a solution!

**Comment by alexanderwallin** [comment]
I should have been resolved in https://github.com/alexanderwallin/lioness/commit/edd64cd0b9fa8998940c197228d1539de7133b0f, so rebase on top of master if you want to update the examples app!

**Comment by iszak** [comment]
@alexanderwallin rebased

**Comment by alexanderwallin** [comment]
I created an issue for the examples page here: https://github.com/alexanderwallin/lioness/issues/9

**Comment by alexanderwallin** [comment]
I'll add you as a collaborator on the repo if you like?

**Comment by iszak** [comment]
@alexanderwallin I am not sure if it will change the workflow much, I would still like peer review on any changes (unless it's non-breaking)

**Comment by alexanderwallin** [comment]
I'll gladly review. I have invited you, respond as you please!

**Pull request merged**
